### ISSUE TITLE
'Unable to merge' error from some PDF documents

### ISSUE THREAD

**Issue by alexaryn** [aryn-ai/sycamore#82]
**Describe the bug**
Running code like this:
```
ds = ctx.read.binary(paths,
                     binary_format='pdf',
                     filesystem=fsys) \
       .partition(partitioner=UnstructuredPdfPartitioner()) \
       .extract_entity(entity_extractor=OpenAIEntityExtractor("title",
           llm=davinci_llm, prompt_template=title_template)) \
       .explode() \
       .embed(embedder=SentenceTransformerEmbedder(
                           model_name='all-MiniLM-L6-v2',
                           batch_size=100))
```
I encountered the following exception multiple times:
```
Task failed with retryable exception: TaskID(4bd0097babf65a07ffffffffffffffffffffffff01000000).
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1191, in ray._raylet.execute_dynamic_generator_and_store_task_outputs
  File "python/ray/_raylet.pyx", line 3684, in ray._raylet.CoreWorker.store_task_outputs
  File "/home/alex/.cache/pypoetry/virtualenvs/sycamore-ai--WPxFaDf-py3.11/lib/python3.11/site-packages/ray/data/_internal/execution/operators/map_operator.py", line 415, in _map_task
    for b_out in fn(iter(blocks), ctx):
  File "/home/alex/.cache/pypoetry/virtualenvs/sycamore-ai--WPxFaDf-py3.11/lib/python3.11/site-packages/ray/data/_internal/planner/plan_udf_map_op.py", line 76, in do_map
    yield from transform_fn(blocks, ctx, *fn_args, **fn_kwargs)
  File "/home/alex/.cache/pypoetry/virtualenvs/sycamore-ai--WPxFaDf-py3.11/lib/python3.11/site-packages/ray/data/_internal/planner/flat_map.py", line 32, in fn
    yield output_buffer.next()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/.cache/pypoetry/virtualenvs/sycamore-ai--WPxFaDf-py3.11/lib/python3.11/site-packages/ray/data/_internal/output_buffer.py", line 74, in next
    block = self._buffer.build()
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/.cache/pypoetry/virtualenvs/sycamore-ai--WPxFaDf-py3.11/lib/python3.11/site-packages/ray/data/_internal/delegating_block_builder.py", line 64, in build
    return self._builder.build()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/.cache/pypoetry/virtualenvs/sycamore-ai--WPxFaDf-py3.11/lib/python3.11/site-packages/ray/data/_internal/table_block.py", line 123, in build
    return self._concat_tables(tables)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/.cache/pypoetry/virtualenvs/sycamore-ai--WPxFaDf-py3.11/lib/python3.11/site-packages/ray/data/_internal/arrow_block.py", line 128, in _concat_tables
    return transform_pyarrow.concat(tables)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/.cache/pypoetry/virtualenvs/sycamore-ai--WPxFaDf-py3.11/lib/python3.11/site-packages/ray/data/_internal/arrow_ops/transform_pyarrow.py", line 254, in concat
    table = pyarrow.concat_tables(blocks, promote=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/table.pxi", line 5371, in pyarrow.lib.concat_tables
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Unable to merge: Field binary_representation has incompatible types: string vs binary
```
After the error, I end up with 3 Ray processes each using 100% CPU and never exiting.

**To Reproduce**
Contact me for the set of PDF documents that triggers the error.

**Expected behavior**
Documents indexed into OpenSearch.

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by bsowell** [comment]
Hmm. Looks like the binary_representation is being set to a string as opposed to bytes. If you force evaluation before the explode (e.g. by running show or count after extract entity), does is still fail? Trying to see if we can narrow down which transform is setting it incorrectly. 

Long term this is the type compatibility issue that @bohou-aryn has been thinking about, but I bet there is a short term fix -- if nothing else we could utf-8 encode text before stuffing it in binary_representation.

**Comment by bsowell** [comment]
Just grepping through the code, I wonder if the issue is here: 

https://github.com/aryn-ai/sycamore/blob/51e2f67d4dc884fee389fc02712f7eeedef9ad83/sycamore/transforms/partition.py#L51

**Comment by pparmar30** [comment]
> Just grepping through the code, I wonder if the issue is here:
> 
> https://github.com/aryn-ai/sycamore/blob/51e2f67d4dc884fee389fc02712f7eeedef9ad83/sycamore/transforms/partition.py#L51

I think that is where the issue is! Probably just need to encode it as a quick fix.

**Comment by alexaryn** [comment]
I'm running it with .encode("utf-8") added and it's looking better.  I'm still puzzled by the switcheroo between text and binary.  Also, shouldn't L52 specify UTF-8?
