### ISSUE TITLE
Another 'Unable to merge' problem

### ISSUE THREAD

**Issue by alexaryn** [aryn-ai/sycamore#85]
**Describe the bug**
```
Traceback (most recent call last):
  File "/home/alex/github/sycamore/foobar.py", line 93, in <module>
    ds.write.opensearch(
  File "/home/alex/github/sycamore/sycamore/writer.py", line 20, in opensearch
    os.execute()
  File "/home/alex/github/sycamore/sycamore/writers/opensearch.py", line 48, in execute
    dataset.write_datasource(
  File "/home/alex/.cache/pypoetry/virtualenvs/sycamore-ai--WPxFaDf-py3.11/lib/python3.11/site-packages/ray/data/dataset.py", line 2944, in write_datasource
    ).materialize()
      ^^^^^^^^^^^^^
  File "/home/alex/.cache/pypoetry/virtualenvs/sycamore-ai--WPxFaDf-py3.11/lib/python3.11/site-packages/ray/data/dataset.py", line 4149, in materialize
    copy._plan.execute(force_read=True)
  File "/home/alex/.cache/pypoetry/virtualenvs/sycamore-ai--WPxFaDf-py3.11/lib/python3.11/site-packages/ray/data/_internal/plan.py", line 591, in execute
    blocks = execute_to_legacy_block_list(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/.cache/pypoetry/virtualenvs/sycamore-ai--WPxFaDf-py3.11/lib/python3.11/site-packages/ray/data/_internal/execution/legacy_compat.py", line 116, in execute_to_legacy_block_list
    block_list = _bundles_to_block_list(bundles)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/.cache/pypoetry/virtualenvs/sycamore-ai--WPxFaDf-py3.11/lib/python3.11/site-packages/ray/data/_internal/execution/legacy_compat.py", line 349, in _bundles_to_block_list
    for ref_bundle in bundles:
  File "/home/alex/.cache/pypoetry/virtualenvs/sycamore-ai--WPxFaDf-py3.11/lib/python3.11/site-packages/ray/data/_internal/execution/interfaces.py", line 548, in __next__
    return self.get_next()
           ^^^^^^^^^^^^^^^
  File "/home/alex/.cache/pypoetry/virtualenvs/sycamore-ai--WPxFaDf-py3.11/lib/python3.11/site-packages/ray/data/_internal/execution/streaming_executor.py", line 129, in get_next
    raise item
  File "/home/alex/.cache/pypoetry/virtualenvs/sycamore-ai--WPxFaDf-py3.11/lib/python3.11/site-packages/ray/data/_internal/execution/streaming_executor.py", line 187, in run
    while self._scheduling_loop_step(self._topology) and not self._shutdown:
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/.cache/pypoetry/virtualenvs/sycamore-ai--WPxFaDf-py3.11/lib/python3.11/site-packages/ray/data/_internal/execution/streaming_executor.py", line 235, in _scheduling_loop_step
    process_completed_tasks(topology)
  File "/home/alex/.cache/pypoetry/virtualenvs/sycamore-ai--WPxFaDf-py3.11/lib/python3.11/site-packages/ray/data/_internal/execution/streaming_executor_state.py", line 333, in process_completed_tasks
    op.notify_work_completed(ref)
  File "/home/alex/.cache/pypoetry/virtualenvs/sycamore-ai--WPxFaDf-py3.11/lib/python3.11/site-packages/ray/data/_internal/execution/operators/task_pool_map_operator.py", line 65, in notify_work_completed
    task.output = self._map_ref_to_ref_bundle(ref)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/.cache/pypoetry/virtualenvs/sycamore-ai--WPxFaDf-py3.11/lib/python3.11/site-packages/ray/data/_internal/execution/operators/map_operator.py", line 357, in _map_ref_to_ref_bundle
    all_refs = list(ray.get(ref))
                    ^^^^^^^^^^^^
  File "/home/alex/.cache/pypoetry/virtualenvs/sycamore-ai--WPxFaDf-py3.11/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/alex/.cache/pypoetry/virtualenvs/sycamore-ai--WPxFaDf-py3.11/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/.cache/pypoetry/virtualenvs/sycamore-ai--WPxFaDf-py3.11/lib/python3.11/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ArrowInvalid): ray::Map(BinaryScan._to_document)->Map(ray_callable)->Map(ray_callable)->FlatMap(ray_callable)() (pid=70286, ip=10.1.10.95)
  File "/home/alex/.cache/pypoetry/virtualenvs/sycamore-ai--WPxFaDf-py3.11/lib/python3.11/site-packages/ray/data/_internal/execution/operators/map_operator.py", line 415, in _map_task
    for b_out in fn(iter(blocks), ctx):
  File "/home/alex/.cache/pypoetry/virtualenvs/sycamore-ai--WPxFaDf-py3.11/lib/python3.11/site-packages/ray/data/_internal/planner/plan_udf_map_op.py", line 76, in do_map
    yield from transform_fn(blocks, ctx, *fn_args, **fn_kwargs)
  File "/home/alex/.cache/pypoetry/virtualenvs/sycamore-ai--WPxFaDf-py3.11/lib/python3.11/site-packages/ray/data/_internal/planner/flat_map.py", line 32, in fn
    yield output_buffer.next()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/.cache/pypoetry/virtualenvs/sycamore-ai--WPxFaDf-py3.11/lib/python3.11/site-packages/ray/data/_internal/output_buffer.py", line 74, in next
    block = self._buffer.build()
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/.cache/pypoetry/virtualenvs/sycamore-ai--WPxFaDf-py3.11/lib/python3.11/site-packages/ray/data/_internal/delegating_block_builder.py", line 64, in build
    return self._builder.build()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/.cache/pypoetry/virtualenvs/sycamore-ai--WPxFaDf-py3.11/lib/python3.11/site-packages/ray/data/_internal/table_block.py", line 123, in build
    return self._concat_tables(tables)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/.cache/pypoetry/virtualenvs/sycamore-ai--WPxFaDf-py3.11/lib/python3.11/site-packages/ray/data/_internal/arrow_block.py", line 128, in _concat_tables
    return transform_pyarrow.concat(tables)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/.cache/pypoetry/virtualenvs/sycamore-ai--WPxFaDf-py3.11/lib/python3.11/site-packages/ray/data/_internal/arrow_ops/transform_pyarrow.py", line 254, in concat
    table = pyarrow.concat_tables(blocks, promote=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/table.pxi", line 5371, in pyarrow.lib.concat_tables
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Unable to merge: Field properties has incompatible types: struct<coordinates: struct<layout_height: double, layout_width: double, points: list<item: list<item: double>>, system: string>, element_id: string, filename: string, filetype: string, page_number: int64, path: string> vs struct<coordinates: struct<layout_height: double, layout_width: double, points: list<item: list<item: double>>, system: string>, element_id: string, filename: string, filetype: string, page_number: int64, path: string, title: string>
```

**To Reproduce**
```
ds = ctx.read.binary(paths,
                     binary_format='pdf',
                     filesystem=fsys) \
       .partition(partitioner=UnstructuredPdfPartitioner()) \
       .extract_entity(entity_extractor=OpenAIEntityExtractor("title",
           llm=davinci_llm, prompt_template=title_template)) \
       .explode() \
       .embed(embedder=SentenceTransformerEmbedder(
                           model_name='all-MiniLM-L6-v2',
                           batch_size=100))
```

**Expected behavior**
No error.

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**
If you need the PDFs, I can provide them.

**Comment by bohou-aryn** [comment]
**Let's keep this issue open.**
This is the known bug for concatenating pyarrow tables under ray dataset scenario.
When concatenating pyarrow tables, any data type different would cause failure, e.g.
```python
struct<a: struct<a1:int, a2:int>> vs struct<a: struct<a1:int>>, field "a" would be treated as different types.
```
we need guarantee all schame across different blocks are consistent.

**Comment by alexaryn** [comment]
Can we use this?  https://arrow.apache.org/docs/python/generated/pyarrow.unify_schemas.html
